global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics exposed by consumer.py on port 8000
  - job_name: kafka_consumer
    static_configs:
      - targets: ["host.docker.internal:8000"]
        labels:
          service: stock-market-consumer

  # Scrape metrics exposed by anomaly_detector.py on port 8001
  - job_name: anomaly_detector
    static_configs:
      - targets: ["host.docker.internal:8001"]
        labels:
          service: anomaly-detector

  # Redpanda internal metrics
  - job_name: redpanda
    static_configs:
      - targets: ["redpanda:9644"]
        labels:
          service: redpanda
